# Generated by Django 3.1.2 on 2023-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230609_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='eventos'),
        ),
    ]
