# Generated by Django 4.2.2 on 2023-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tipo_cosultas_contactanos_tipo_consultas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='stock',
            field=models.IntegerField(default=50),
        ),
    ]
