# Generated by Django 4.2.2 on 2023-06-23 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}-[0-9kK]{1}$', 'El RUT debe tener el siguiente formato: 19999999-9 o 9999999-9 o 19999999-K.')]),
        ),
    ]
