# Generated by Django 3.1.2 on 2023-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_eventos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
