# Generated by Django 3.1.2 on 2023-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230630_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
