# Generated by Django 3.1.2 on 2023-07-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230701_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
